---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Work
- type: directory
  path: content/exhibit
  label: Exhibit
  create: all
  match: "**/*"
  new_doc_ext: json
  templates:
  - rich-text
- type: document
  path: content/work/identity.json
  label: Identity
- type: heading
  label: Play
- type: document
  path: content/play/photo.json
  label: photos
- type: directory
  path: content/play/dj
  label: DJ
  create: all
  match: "**/*"
  new_doc_ext: json
  templates:
  - audio
- type: heading
  label: About
- type: document
  path: content/about/resume.json
  label: Resume
- type: document
  path: content/about/contact.json
  label: Contact
upload_dir: ''
public_path: ''
front_matter_path: s3.amazonaws.com/cms.thisispete.com
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
