---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Work
- type: directory
  path: content/work
  label: posts
  create: all
  match: "**/*"
  new_doc_ext: ".json"
- type: heading
  label: Play
- type: directory
  path: content/play
  label: posts
  create: all
  match: "**/*"
  new_doc_ext: ".json"
- type: heading
  label: About
- type: document
  path: content/about/resume.json
  label: Resume
  match: "**/*"
- type: document
  path: content/about/contact.json
  label: Contact
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
